apiVersion: apps/v1
kind: ReplicaSet
metadata:
  name: frontend
  labels:
    app: sampleapp
    tier: frontend
spec:
  replicas: 3
  selector:
    matchLabels:
      tier: frontend
  template:
    metadata:
      labels:
        tier: frontend
    spec:
      containers:
      - name: apache
        image: nginx
        
        ----
        
apiVersion: v1
kind: Service
metadata:
  name: my-service
spec:
  selector:
    tier: frontend
  ports:
   - protocol: TCP
     port: 8080
     targetPort: 80
  clusterIP: 10.105.12.2
  type: LoadBalancer
