apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: my-pvc2
spec:
  storageClassName: standard
  volumeName: my-pv
  accessModes:
    - ReadOnlyMany
  resources:
    requests:
      storage: 512Mi
