apiVersion: v1
kind: Pod
metadata:
  name: myschedulerpod
  labels:
    name: multischeduler-example
spec:
  schedulerName: customschedule
  containers:
  - name: cont
    image: nginx
    ports:
      - containerPort: 80
