apiVersion: v1
kind: Pod
metadata:
  name: envar-demo
spec:
  containers:
  - name: envar-demo-container
    image: hello-world
    env:
    - name: Variable1
      value: "value1"
    - name: Variable2
      value: "value2"
